project_id = "undppzthskqsikywqvwn"

[functions.vapi-proxy]
verify_jwt = true

[functions.vapi-webhook]
verify_jwt = false

[functions.vapi-sync]
verify_jwt = true

[functions.vapi-file-upload]
verify_jwt = true

[functions.vapi-kb-sync]
verify_jwt = true

[functions.vapi-kb-unsync]
verify_jwt = true

[functions.vapi-file-delete]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.twilio-sms]
verify_jwt = true
